name: Go

# Triggers the workflow on push or pull request events
on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
      
    - name: Install lint
      run: go get -u golang.org/x/lint/golint
        
    - name: lint
      run: golint -set_exit_status=true ./...

    - name: Build
      run: go build -v ./...
